name: Scheduled Events

on:
  schedule:
    - cron: '0/30 * * * *'   # every 30 minutes
  workflow_dispatch:           # manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  health-check:
    if: github.ref_name != 'main'       # <-- only run if branch is NOT main
    runs-on: ubuntu-latest
    environment: PROD_JIRA_API_TOKEN
    env:
      TZ: America/Denver  # Mountain Time (MDT/MST)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}   # pulls the current branch

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Jira Client
        run: python entrypoints/run_scheduled.py
        env:
          PROD_JIRA_API_TOKEN: ${{ secrets.PROD_JIRA_API_TOKEN }}
